import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import NavBar from "@app/components/Navbar";
import Footer from "@app/components/Footer";
import { Box } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: "signin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NavBar />

          <main>
            <Box as="div" minHeight={"80vh"}>
              {children}
            </Box>
          </main>

          <footer>
            <Footer />
          </footer>
        </Providers>
      </body>
    </html>
  );
}
